name: Daily Telegram Bot Report

on:
  schedule:
    - cron: '0 */1 * * *'  # Chạy mỗi giờ một lần (để đảm bảo liên tục)
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  send-report:
    runs-on: ubuntu-latest  # Máy ảo Ubuntu
    timeout-minutes: 1440  # Thời gian chạy tối đa 24h (1440 phút)

    steps:
      # Bước 1: Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Phiên bản Python của bạn

      # Bước 3: Cài đặt thư viện
      - name: Install dependencies
        run: |
          pip install python-telegram-bot
          pip install requests
          pip install beautifulsoup4
          pip install schedule
          pip install pandas
          pip install python-crontab  # Thêm thư viện hỗ trợ lập lịch

      # Bước 4: Chạy bot liên tục
      - name: Run Telegram Bot Continuously
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Token lưu trong GitHub Secrets
          CHAT_ID: ${{ secrets.CHAT_ID }}      # ID nhóm/chat Telegram
        run: |
          while true; do
            python tintuc.py  # Tên file chính của bạn
            sleep 3600  # Chờ 1 tiếng trước khi chạy lại (3600 giây)
          done

      # Bước 5: Thông báo trạng thái
      - name: Notify Telegram
        if: always()  # Chạy dù thành công hay thất bại
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"chat_id":"${{ secrets.CHAT_ID }}", "text":"GitHub Actions: ${{ job.status }} - Bot đã chạy xong một chu kỳ"}' \
          "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage"
